インプレスに変更
h-kwhr-web/ichiyasaGitSample pull request #1
Opened 2022-08-13 17:55 UTC by h-kwhr-web

変更内容：インプレスにしました

2022-08-14 09:52 UTC, piyo-s commented
LTGM

2022-08-14 09:53 UTC, piyo-s reviewed
いいとおもう

2022-08-14 09:53 UTC, piyo-s commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
lgtm

2022-08-14 10:04 UTC, piyo-s requested changes
☆(株)インプレス☆にしてくれん？

2022-08-14 10:30 UTC, h-kwhr-web commented on index.html
> +                        <p>☆(株)インプレス☆ イベントセミナー会場</p>
修正しました

2022-08-19 06:40 UTC, piyo-s commented on index.html
> +                        <p>☆(株)インプレス☆ イベントセミナー会場</p>
確認しました

2022-08-19 06:43 UTC, piyo-s approved these changes

2022-08-19 06:45 UTC, merged